general.import = [
    # "~/.config/alacritty/themes/base16_default_dark.toml"

    # TODO: remove???
    # "~/.config/alacritty/themes/tokyo_night_storm.toml"
]

general.live_config_reload = true

[cursor]
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

# TODO: set up pretty
# [font]
# size = 11

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations_theme_variant = "Dark"
opacity = 0.8
