" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

"Plugins
call plug#begin('/usr/share/vim/plugged')

Plug 'jiangmiao/auto-pairs'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"colorschemes
Plug 'morhetz/gruvbox'
Plug 'joshdick/onedark.vim'

call plug#end()

"Visual
"set termguicolors
syntax on
colorscheme onedark
"set background=dark
set number
set expandtab
set tabstop=2

set incsearch
set hlsearch

"Copy Paste
""vnoremap <C-c> "+y
""map <C-v> "+P
""nnoremap <C-@> :call system("wl-copy", @")<CR>
"xnoremap <silent> <C-@> :w !wl-copy<CR><CR>

