general {
  # Avoid starting multiple hyprlock instances
  lock_cmd = pidof hyprlock || hyprlock
  # Lock before suspend
  before_sleep_cmd = loginctl lock-session
  # To avoid having to press a key twice to turn on the display
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = $NOTIFICATION_TIMEOUT
  # Make notifications stay until back
  on-timeout = makoctl mode -a away
  on-resume = makoctl mode -r away
}

listener {
  timeout = $SCREEN_TIMEOUT
  # Make screen off until back
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = $LOCK_TIMEOUT
  on-timeout = hyprlock
}
