save-position-on-quit
fullscreen

# === Video ===
vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
hwdec=vulkan

vd-lavc-dr=yes
vd-lavc-film-grain=gpu

tone-mapping=bt.2446a

deband=yes
deband-iterations=4
deband-threshold=48
deband-range=16

# === Subtitles ===
slang=en,eng,en-US,ru,rus
subs-fallback-forced=no
sub-ass-override=force
sub-font="Noto Serif"
sub-font-size=48
sub-color="#FFFFFFFF"
sub-border-size=1.5
sub-shadow-offset=1
sub-shadow-color="#33000000"
sub-spacing=0.5
sub-margin-y=50
sub-auto=fuzzy

# === Audio ===
ao=pipewire
audio-channels=stereo
alang=en,eng,en-US,ja,jpn,ko,kor
volume=100
