--ozone-platform-hint=auto
--ozone-platform=wayland

--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
--disable-features=UseChromeOSDirectVideoDecoder
--use-vulkan

--ignore-gpu-blocklist
--enable-native-gpu-memory-buffers
--enable-zero-copy
