monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-Audient_Audient_iD4-00.HiFi__Headphones__sink"
      },
      {
        node.name = "alsa_output.usb-Audient_Audient_iD4-00.HiFi__Speaker__sink"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 99
        priority.session = 99
      }
    }
  }
]
