#!/bin/bash

check=$(sudo systemctl is-active wg-quick@arch_wg)

if [ "$1" == check ]
then
  echo "$check"
  exit 
fi

if [ "$1" == fix ]
then
  if [ "$check" == "active" ]
  then
    nmcli c modify KakoyZheParol ipv4.dns 10.0.0.1
    nmcli c up KakoyZheParol
    echo "dns fixed: 10.0.0.1"
    exit
  fi
  if ["$check" == "inactive"] || [ "$check" == "failed" ] 
  then
    nmcli c modify KakoyZheParol ipv4.dns 192.168.1.1
    nmcli c up KakoyZheParol
    echo "dns fixed: 192.168.1.1"
    exit  
  fi
fi 

if [ "$check" == "active" ]
then
  sudo systemctl stop wg-quick@arch_wg
  nmcli c modify KakoyZheParol ipv4.dns 192.168.1.1
  nmcli c up KakoyZheParol
  echo "WireGuard is turn off"
else
  nmcli c modify KakoyZheParol ipv4.dns 10.0.0.1
  nmcli c up KakoyZheParol
  sudo systemctl start wg-quick@arch_wg
  echo "Wireguard is turn on"
fi
